# Generated by Django 4.2.7 on 2023-12-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(upload_to='brands_img', verbose_name='Изображение'),
        ),
    ]
