<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-09 17:00
=======
<<<<<<<< HEAD:import_export/migrations/0001_initial.py
# Generated by Django 4.2.7 on 2023-12-09 17:00
========
# Generated by Django 4.2.4 on 2023-12-12 15:25
>>>>>>>> c1219f96c33c92fc429c6d63e987d700056e8ecc:news/migrations/0001_initial.py
>>>>>>> c1219f96c33c92fc429c6d63e987d700056e8ecc
=======
# Generated by Django 4.2.4 on 2023-12-19 16:09
>>>>>>> 6814f243ba46c80902054d781a23c38394fe4af6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=250, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Фото')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
