# Generated by Django 4.2.7 on 2023-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Соц сеть')),
                ('image', models.ImageField(upload_to='image/', verbose_name='иконка')),
                ('social', models.URLField(blank=True, max_length=150, verbose_name='ссылка')),
            ],
        ),
    ]
