# Generated by Django 4.2.7 on 2023-12-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='category',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cola',
        ),
        migrations.RemoveField(
            model_name='category',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fanta',
        ),
        migrations.RemoveField(
            model_name='category',
            name='juice',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tonic',
        ),
        migrations.RemoveField(
            model_name='category',
            name='water',
        ),
    ]
