# Generated by Django 4.2.7 on 2023-12-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_alcohol_remove_category_coffee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alcohol',
            field=models.BooleanField(default=False, verbose_name='Алкоголь'),
        ),
        migrations.AddField(
            model_name='category',
            name='coffee',
            field=models.BooleanField(default=False, verbose_name='Кофе'),
        ),
        migrations.AddField(
            model_name='category',
            name='cola',
            field=models.BooleanField(default=False, verbose_name='Кока-кола'),
        ),
        migrations.AddField(
            model_name='category',
            name='energy',
            field=models.BooleanField(default=False, verbose_name='Энергетик'),
        ),
        migrations.AddField(
            model_name='category',
            name='fanta',
            field=models.BooleanField(default=False, verbose_name='Фанта'),
        ),
        migrations.AddField(
            model_name='category',
            name='juice',
            field=models.BooleanField(default=False, verbose_name='Соки'),
        ),
        migrations.AddField(
            model_name='category',
            name='sodium',
            field=models.BooleanField(default=False, verbose_name='Лимонад'),
        ),
        migrations.AddField(
            model_name='category',
            name='tonic',
            field=models.BooleanField(default=False, verbose_name='Тоник'),
        ),
        migrations.AddField(
            model_name='category',
            name='water',
            field=models.BooleanField(default=False, verbose_name='Вода'),
        ),
    ]
